# Generated by Django 3.1.7 on 2021-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210310_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
