# Generated by Django 3.1.7 on 2021-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_extenduser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='country',
            field=models.CharField(max_length=255, verbose_name='country'),
        ),
    ]
