# Generated by Django 3.1.7 on 2021-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210318_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
