# Generated by Django 3.1.7 on 2021-03-28 06:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210327_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile_picture',
            field=models.ImageField(upload_to=users.models.upload_path),
        ),
    ]
