# Generated by Django 3.1.7 on 2021-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210328_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='my_test',
            field=models.CharField(blank=True, max_length=255, verbose_name='my_test'),
        ),
    ]
