# Generated by Django 3.2.5 on 2021-07-29 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_extenduser_my_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
