# Generated by Django 3.2.5 on 2021-08-07 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_extenduser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='declined_friends',
            field=models.ManyToManyField(blank=True, related_name='declined', to=settings.AUTH_USER_MODEL),
        ),
    ]
