# Generated by Django 3.2.5 on 2021-07-24 13:40

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('friend_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('user_from', 'user_to'), name='Unique_friend_reques'),
        ),
    ]
