# Generated by Django 3.1.7 on 2021-03-29 14:40

from django.db import migrations, models
import temporary_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=temporary_images.models.upload_path)),
            ],
        ),
    ]
